### ISSUE TITLE
thanos-compact pod error, persistentVolumeClaim volumes are not allowed to be used

### ISSUE THREAD

**Issue by neo-liang-sap** [banzaicloud/banzai-charts#1007]
Hello,

When i was trying to deploy helm charts (to an google cluster) of thanos i got following error:

```
Warning  FailedCreate  6s (x13 over 27s)  replicaset-controller  Error creating: pods "thanos-compact-7db45bcc8b-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "persistentVolumeClaim": persistentVolumeClaim volumes are not allowed to be used]
```

I assume this is due to thanos missing PodSecurityPolicy to access all volumes so i add psp/clusterrole/rolebinding as below (i'm installing thanos chart in namespace of monitoring)

```
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: permit-volumes-all
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enable-thanos-psp
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - permit-volumes-all
  verbs:
  - use


---



# Bind the ClusterRole to the desired set of service accounts.
# Policies should typically be bound to service accounts in a namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-rolebing
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enable-thanos-psp
subjects:
# Example: All service accounts in my-namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
# Example: A specific service account in my-namespace
- kind: ServiceAccount # Omit apiGroup
  name: default
  namespace: monitoring
```

after these i delete deployment of thanos-compact and redeploy, still i'm facing the same error.

Is there anything i need to add?

Thanks!

**Comment by neo-liang-sap** [comment]
Hi,
i fixed my issue by adding following PSP / ClusterRole / RoleBinding , just share with you to see whether you need add some file like this one (i install thanos helm chart in monitoring namespace)

```
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: permit-thanos-volumes-all
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enable-thanos-psp
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - permit-thanos-volumes-all
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-rolebing
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enable-thanos-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
# Example: A specific service account in my-namespace
- kind: ServiceAccount # Omit apiGroup
  name: default
  namespace: monitoring

```
