### ISSUE TITLE
[Thanos Chart] store.metrics.annotations.enabled failes

### ISSUE THREAD

**Issue by ebini** [banzaicloud/banzai-charts#1036]
setting:
```
store:
  metrics:
    annotations:
      enabled: true
```

will throw an error.

on other components no error is thrown.

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.metadata): unknown field "prometheus.io/port" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Deployment.spec.template.metadata): unknown field "prometheus.io/scrape" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]
