### ISSUE TITLE
Thanos Helm Chart - Multiple Store per Time Partition

### ISSUE THREAD

**Issue by iceycake** [banzaicloud/banzai-charts#1040]
**Describe the bug**
According to the readme, the helm chart can deploy multiple store cotnainers by providing a MAP of partitions.  It looks like just 1 store container is deployed w/o the time partition configuration.

**Steps to reproduce the issue:**
In the values file:
```
  timePartioning:
    - min: -2w
      max: ""
    - min: -6w
      max: -2w
    - min: ""
      max: -6w
```

I will assume multiple manifests be generated.  However, only 1 manifest is created and missing the `--max-time` and `--min-time` arguments within that manifest.  Feeling like the following is completely missing.

```
        {{- if $partion.max }}
        - "--max-time={{ $partion.max }}"
        {{- end}}
        {{- if $partion.min }}
        - "--min-time={{ $partion.min }}"
        {{- end}}
```

**Expected behavior**
Multiple manifests are generated along with the `--max-time` and `--min-time` arguments.

**Screenshots**
n/a

**Additional context**
n/a
