### ISSUE TITLE
[thanos] Default Backend config in ingress

### ISSUE THREAD

**Issue by karthikm83** [banzaicloud/banzai-charts#1111]
It would be nice to be able to configure default backend for all ingress objects in thanos chart.

For example, below ingress config is not possible with current ingress templates.
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: my-products
    servicePort: 60001
```
