### ISSUE TITLE
[Cadence] Indention is missing in dynamic config file if passing through values.yaml

### ISSUE THREAD

**Issue by longquanzheng** [banzaicloud/banzai-charts#1187]
**Describe the bug**

I added the dynamic config in values.yaml:
```
dynamicConfig:
  values:
    matching.numTasklistWritePartitions:
      - value: 10
        constraints:
          domainName: "qlong"
          taskListName: "helloWorldGroup"
    matching.numTasklistReadPartitions:
      - value: 10
        constraints:
          domainName: "qlong"
          taskListName: "helloWorldGroup"
  pollInterval: "10s"
```
However the generated dynamic config file is missing the indention before `- value: 10`
The dynamic config is not working without the indention.
As a workaround, I have to put dynamic config in the config_map like this:
```
  dynamic_config.yaml: |-
    matching.numTasklistWritePartitions:
      - value: 10
        constraints:
          domainName: "qlong"
          taskListName: "helloWorldGroup"
    matching.numTasklistReadPartitions:
      - value: 10
        constraints:
          domainName: "qlong"
          taskListName: "helloWorldGroup"
```

**Steps to reproduce the issue:**

Like above 

**Expected behavior**

Using dynamic config in the values.yaml should work without missing indention.

**Screenshots**

<img width="536" alt="Screen Shot 2020-11-10 at 11 17 36 AM" src="https://user-images.githubusercontent.com/4523955/98722794-596e0f00-2346-11eb-833e-f8bee4f2e161.png">

**Additional context**

https://uber-cadence.slack.com/archives/CL22WDF70/p1605029791433500?thread_ts=1603318877.335000&cid=CL22WDF70

**Comment by sagikazarmark** [comment]
It looks like the indentation is indeed removed, but the resulting YAML is actually valid. (Paste that into [yamllint](http://www.yamllint.com/) and it'll tell you it's valid)

We have the following config:

```yaml
dynamicConfig:
  values:
    worker.executionsScannerEnabled:
      - constraints: {}
        value: false
```

and it gets translated into:

```yaml
  dynamic_config.yaml: |-
    worker.executionsScannerEnabled:
    - constraints: {}
      value: false
```

I can see the value being applied in the logs:

```
{"level":"info","ts":"2020-11-09T10:11:18.388Z","msg":"Get dynamic config","name":"worker.executionsScannerEnabled","value":"false","default-value":"false","logging-call-at":"config.go:72"}
```

Now, I haven't investigated it any further, but based on the linked conversation, it's not obvious that the indentation fixed the problem.

@longquanzheng can you please double check if this is actually the problem? I could imagine the yaml parser not handling something correctly in cadence, but it works just fine on my end and the YAML looks valid as well. Thanks!
