### ISSUE TITLE
[Cadence][Bug]Template default to secondary cluster which will not work

### ISSUE THREAD

**Issue by longquanzheng** [banzaicloud/banzai-charts#1275]
**Describe the bug**

According to conversions with several Cadence users, what is applied into k8s by default is
```

clusterMetadata:
  enableGlobalDomain: {{ default .Env.ENABLE_GLOBAL_DOMAIN "false" }}
  failoverVersionIncrement: 10
  masterClusterName: "primary"
  currentClusterName: "secondary"
  clusterInformation:
    primary:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: {{ default .Env.PRIMARY_FRONTEND_SERVICE "cadence" }}:7933
    secondary:
        enabled: true
        initialFailoverVersion: 2
        rpcName: "cadence-frontend"
        rpcAddress: {{ default .Env.SECONDARY_FRONTEND_SERVICE "cadence-secondary" }}:7933

```

This will not work because only master cluster can register domain. Moreover, by default we expect to see Cadence enable global domain with a single cluster, which should be like:
```
clusterMetadata:
  enableGlobalDomain: true
  failoverVersionIncrement: 10
  masterClusterName: "primary"
  currentClusterName: "primary"
  clusterInformation:
    primary:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: {{ default .Env.PRIMARY_FRONTEND_SERVICE "cadence" }}:7933
```

**Steps to reproduce the issue:**
Apply the current helmcart of latest master commit https://github.com/banzaicloud/banzai-charts/commit/335e56b03e222835a76c03156a9e46a009d17f79 into K8s.

**Expected behavior**

by default we expect to see Cadence enable global domain with a single cluster, which should be like:
```
clusterMetadata:
  enableGlobalDomain: true
  failoverVersionIncrement: 10
  masterClusterName: "primary"
  currentClusterName: "primary"
  clusterInformation:
    primary:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: {{ default .Env.PRIMARY_FRONTEND_SERVICE "cadence" }}:7933
```

**Screenshots**
<img width="1090" alt="Screen Shot 2021-07-30 at 9 54 31 AM" src="https://user-images.githubusercontent.com/4523955/127686299-21e7847a-0df4-4fd2-9f3e-2b4b8e6dcb47.png">

**Additional context**
https://uber-cadence.slack.com/archives/CL22WDF70/p1627655351007800?thread_ts=1627468874.236400&cid=CL22WDF70
