### ISSUE TITLE
Cadence servicemonitor additional labels didn't work

### ISSUE THREAD

**Issue by git-hulk** [banzaicloud/banzai-charts#1291]
**Describe the bug**

When deploying cadence Helm chart with server.meitrics.serviceMonitor.additionalLabels in values.yaml, the chart fails unless the value is a string, in which case the label is not created.

**Steps to reproduce the issue:**
Edit values.yaml and add additionalLabels as map value(s).

```yaml
server:
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: "promethues"
```
and install the helm charts would get the error：

```shell
Error: YAML parse error on cadence/templates/server-service-monitor.yaml: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context
```

**Expected behavior**

The additionalLables should be created in the servicemonitor.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by pregnor** [comment]
[Moved here from a comment on the PR.]

Regarding the original issue:
Have you tested the original implementation with the following approach?
```yaml
server:
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels: |
        release: "promethues"
```
(Note the extra pipe `|` character after the `additionalLabels` key.)

I believe this ☝️  should work (although I didn't have time to test it), because the current implementation embeds the exact YAML source - which is defined under the `additionalLabels` key - as is without changing it and with a multiline string approach you should be able to define YAML key-value pairs conforming to the label schema as a single multiline string in the values file, being embedded as raw YAML, thus becoming key-value pairs after template substitution.

We are using this raw YAML embedding approach in other charts/contexts as well. It has its pros and cons compared to the structured key-value approach, I think in this particular context both are viable.
I don't favor any of the two over the other, but due to the generality I would only change the existing implementation if there are significant gains of the change.

**Comment by git-hulk** [comment]
```
server:
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels: |
        release: "promethues"
```

also got the same error, it's really weird that raw yaml didn't work, can you have a try?
