### ISSUE TITLE
Server Job fails on different nodeSelectors

### ISSUE THREAD

**Issue by flashpixx** [banzaicloud/banzai-charts#1318]
**Describe the bug**

I run the helm chart with a nodeSelector, so the server-job runs on a different node than in my case cassandra, but the job fails every time. I set these values:

```yaml
cadence:
  server:
    nodeSelector:
      <my node key: <my node value>
```

**Steps to reproduce the issue:**

Apply the values above 

**Expected behavior**

Server-Job should run also on different kind of nodes, it my helpful if the nodeSelector can be set as well for the server-job

**Additional context**

I try this with helm chart version 0.23.0 and 0.22.1

**Comment by akijakya** [comment]
Hi!

I tried to reproduce the bug with chart version 0.22.1 on AWS by creating a cluster with nodes of different instance types, and using the `node.kubernetes.io/instance-type` label to put Cadence pods on a node of a specific instance type and for me it worked multiple times. My specific values were:

``` yaml
cadence:
  server:
    nodeSelector:
      node.kubernetes.io/instance-type: m4.large
```

Could you provide more details (node description, pod description and helm chart values) so we can take a look what might went wrong for you?
