### ISSUE TITLE
Drone: webhooks are registered with wrong path so they don't work

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/banzai-charts#249]
Currently Drone is exposed to the Internet with the following Ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-drone
  namespace: default
  labels:
    release: {{ .Release.Name }}

  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.frontend.rule.type: PathPrefixStrip

spec:
  rules:
    - http:
        paths:
          - path: /build
            backend:
             serviceName: {{ .Release.Name }}-drone
             servicePort: 80
```

If the host is `https://pipeline.banzaicloud.com/` Drone webhooks are getting registered with the path `https://pipeline.banzaicloud.com/hook` but instead, they should be registered with `https://pipeline.banzaicloud.com/build/hook` since the whole drone stuff is moved behind `/build`.
