### ISSUE TITLE
Feature Request: External Configuration Documentation

### ISSUE THREAD

**Issue by BertieW** [banzaicloud/banzai-charts#278]
---
name: Documentation of Adding Authentication Backends via External Config

---

**Is your feature request related to a problem? Please describe.**
Using the External Configuration Example provided at https://banzaicloud.github.io/bank-vaults/ unable to get vault to authenticate with GitHub via the UI. Using bank-vaults configure command with the example file with values and tokens set to our organisation was likewise unsuccessful. 

**Describe the solution you'd like**
A working example for configuring GitHub auth backend and an LDAP backend.

**Describe alternatives you've considered**
A manual configuration is possible but it would be quite useful to take advantage of bank-vaults functionality to stand up a vault instance in k8 that would be hooked into an authentication backend at boot. 

**Additional context**
Sample of the config used to set up github stolen shamelessly from above:

>    auth:
>    - type: github
>     config:
>       organization: xxxxxxx
>      map:
>         teams:
>            dev: dev
>        users:
>           bertiew: root

When deployed with this config, attempts to authenticate with GitHub via the UI produces an error about a missing token.

**Comment by bonifaido** [comment]
I have successfully run this configuration for example for Github:

```yaml
  externalConfig:
    # Allows creating policies in Vault which can be used later on in roles
    # for the Kubernetes based authentication.
    # See https://www.vaultproject.io/docs/concepts/policies.html for more information.
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
    auth:
      - type: kubernetes
        # Allows creating roles in Vault which can be used later on for the Kubernetes based
        # authentication.
        # See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
        # more information.
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
      # Allows creating team mappings in Vault which can be used later on for the GitHub 
      # based authentication.
      # See https://www.vaultproject.io/docs/auth/github.html#configuration for
      # more information.
      - type: github
        config:
          organization: banzaicloud
        map:
          # Map the banzaicloud dev team on GitHub to the dev policy in Vault
          teams:
            dev: dev
          # Map myself to the above allow_secrets policy in Vault
          users:
            bonifaido: allow_secrets

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
```
