### ISSUE TITLE
Warnings with Helm 2.11.0

### ISSUE THREAD

**Issue by sebastien-prudhomme** [banzaicloud/banzai-charts#508]
Hi,

Trying some of your charts to see if Pipeline is a good option for my use case.

I'm using Helm 2.11.0 and found warnings in some of your charts.

For instance with the `pipeline`chart:

```
2018/11/23 12:20:48 warning: destination for annotations is a table. Ignoring non-table value <nil>
```

The problem come from pipeline/values.yaml:

```
ingress:
  enabled: false
  annotations:
    #traefik.frontend.rule.type: PathPrefix
```

Helm needs accolades if by default there is no values: `annotations: {}`

Same problem in mysql/values.yaml: `initializationFiles: {}`
