### ISSUE TITLE
Using vault-secrets-webhook with vault running as SaaS

### ISSUE THREAD

**Issue by Johnch9** [banzaicloud/banzai-charts#618]
In our deployment we have vault running in its own K8s cluster, so we will be running vault as SaaS.  

Does vault-secrets-webhook support this deployment model and if it does is there any additional config I need to get it working?

I added a load balancer endpoint to the cluster to expose vault externally and with the vault addr set to the load balancer endpoint I'm seeing the following:
If I deploy the example hello-secrets to the k8s cluster running vault then everything works perfectly.  

Deploying to a different k8s cluster fails with the following error:

2019/01/20 10:22:11 Failed to request new Vault token Error making API request.

URL: PUT https://<ip of vault exposed as loadbalancer>:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* lookup failed: [invalid bearer token, square/go-jose: error in cryptographic primitive]

**Comment by bonifaido** [comment]
Hi @Johnch9,

in this setup the Vault instance in the separate cluster has to be configured, so it can lookup the JWT tokens and review their roles in the sub-clusters, see the following example how to do this with bank-vaults: https://github.com/banzaicloud/bank-vaults/blob/master/vault-config.yml#L13 You will have to mount the kubernetes auth backedn as many times (and as many ways) as many seperate clusters you have.

Although I never tried this setup (which is very good architecture by the way and should be considered a best practice) vault-secrets-webhook and the vault-env binary should support this. Deploy a webhook to every cluster and annotate the pod specifications in those clusters with the following annotations (similarly to https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-deployment.yaml#L15):

```yaml
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault-load-balancer.your.domain:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true" # we don't support custom CA currently, so you should have a proper cert on the LB, or use this annotation right now
        vault.security.banzaicloud.io/vault-path: "kubernetes-cluster-1"
```

Please try this and come back with the results, I'm very interested.
