### ISSUE TITLE
Operator pod fails to start from tag 0.4.4 onwards

### ISSUE THREAD

**Issue by ilyache** [banzaicloud/banzai-charts#623]
The operator pod fails to readiness probes. 

Log:
```
╰─ kubectl logs -f vault-operator-7bc8ff4788-ckcg6
{"level":"info","ts":1548157054.9720583,"logger":"cmd","msg":"Go Version: go1.11.4"}
{"level":"info","ts":1548157054.9721096,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1548157054.972122,"logger":"cmd","msg":"operator-sdk Version: v0.3.0"}
{"level":"info","ts":1548157054.9721391,"logger":"cmd","msg":"Watched namespace: "}
{"level":"info","ts":1548157054.9724245,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1548157055.0102901,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1548157055.0167553,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1548157055.0390944,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1548157055.039443,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"vault-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1548157055.0395703,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1548157055.039662,"logger":"cmd","msg":"Liveness probe listening on: 8080"}
{"level":"info","ts":1548157055.1398392,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"vault-controller"}
{"level":"info","ts":1548157055.2401438,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"vault-controller","worker count":1}
{"level":"info","ts":1548157055.2403579,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"default","Request.Name":"vault"}
```

Events:
```
Events:
  Type     Reason                 Age               From                                     Message
  ----     ------                 ----              ----                                     -------
  Normal   Scheduled              36s               default-scheduler                        Successfully assigned vault-operator-7bc8ff4788-ckcg6 to ip-172-20-102-123.ec2.internal
  Normal   SuccessfulMountVolume  36s               kubelet, ip-172-20-102-123.ec2.internal  MountVolume.SetUp succeeded for volume "vault-operator-token-c4crl"
  Normal   Pulled                 36s               kubelet, ip-172-20-102-123.ec2.internal  Container image "banzaicloud/vault-operator:latest" already present on machine
  Normal   Created                36s               kubelet, ip-172-20-102-123.ec2.internal  Created container
  Normal   Started                36s               kubelet, ip-172-20-102-123.ec2.internal  Started container
  Warning  Unhealthy              5s (x3 over 25s)  kubelet, ip-172-20-102-123.ec2.internal  Readiness probe failed: stat: can't stat '/tmp/operator-sdk-ready': No such file or directory
```

The manifest I'm using:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-operator
  template:
    metadata:
      labels:
        name: vault-operator
    spec:
      serviceAccountName: vault-operator
      containers:
        - name: vault-operator
          image: banzaicloud/vault-operator:0.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - vault-operator
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            # OPERATOR_NAMESPACE is here only for backward compatibility, the new SDK uses WATCH_NAMESPACE instead
            #            - name: OPERATOR_NAMESPACE
            #              value: ""
            - name: WATCH_NAMESPACE
              value: ""
            - name: VAULT_ADDR
              value: http://vault.default:8200
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-operator"
```

This happens in the following images:
- banzaicloud/vault-operator:0.4.4
- banzaicloud/vault-operator:0.4.5

When I downgrade to 0.4.3, the operator starts up fine. Please let me know if any additional information is needed.
