### ISSUE TITLE
indentation issue for tls secret

### ISSUE THREAD

**Issue by devlounge** [banzaicloud/banzai-charts#628]
In vault-secrets-webhook/chart/templates/apiservice-webhook.yaml:

```
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ template "vault-secrets-webhook.fullname" . }}
  type: kubernetes.io/tls  <= Unindent here
```
