### ISSUE TITLE
vaul-secret-webhook doesn't read deployment annotations

### ISSUE THREAD

**Issue by lantier** [banzaicloud/banzai-charts#652]
The Helm Chart for the tool deployed successfully in it's namespace (vshw), the problem is with the example application "hello-secrets"

Using the following YAML, the annotations aren't being read and the POD is deployed with the envs VAULT_ADDR, VAULT_PATH and VAULT_ROLE in blank

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"
```

I enabled DEBUG in Webhook and it shows the following:

```
2019/02/06 13:51:12 [DEBUG] json patch for request 43c3951d-2a16-11e9-85a4-42010a9e0022: [{"op":"add","path":"/spec/volumes/1","value":{"emptyDir":{"medium":"Memory"},"name":"vault-env"}},{"op":"add","path":"/spec/initContainers","value":[{"command":["sh","-c","cp /usr/local/bin/vault-env /vault/"],"image":"banzaicloud/vault-env:latest","imagePullPolicy":"IfNotPresent","name":"copy-vault-env","resources":{},"volumeMounts":[{"mountPath":"/vault/","name":"vault-env"}]}]},{"op":"add","path":"/spec/containers/0/volumeMounts/1","value":{"mountPath":"/vault/","name":"vault-env"}},{"op":"add","path":"/spec/containers/0/args","value":["sh","-c","echo $AWS_SECRET_ACCESS_KEY \u0026\u0026 echo going to sleep... \u0026\u0026 sleep 10000"]},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"VAULT_ROLE","value":"default"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"VAULT_PATH","value":"kubernetes"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"VAULT_SKIP_VERIFY"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"VAULT_ADDR"}},{"op":"remove","path":"/spec/containers/0/command/2"},{"op":"remove","path":"/spec/containers/0/command/1"},{"op":"replace","path":"/spec/containers/0/command/0","value":"/vault/vault-env"}]
```
In hello-secrets pod:

```
    env:
    - name: AWS_SECRET_ACCESS_KEY
      value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
    - name: VAULT_ADDR
    - name: VAULT_SKIP_VERIFY
    - name: VAULT_PATH
      value: kubernetes
    - name: VAULT_ROLE
      value: default
```

```
2019/02/06 13:43:48 Failed to request new Vault token Put https://127.0.0.1:8200/v1/auth/kubernetes/login: dial tcp 127.0.0.1:8200: connect: connection refused
```

Any tips in what is wrong?
I'm using GKE Kubernetes.
