### ISSUE TITLE
Wrong annotations in the BanzaiCloud blog

### ISSUE THREAD

**Issue by prometherion** [banzaicloud/banzai-charts#684]
I'm opening the issue here to report this [post](https://banzaicloud.com/blog/inject-secrets-into-pods-vault/), I think it's strictly related.

There's a typo regarding the example: `annotations` keys that should enable secrets injection should be placed in `.spec.template.metadata.annotations`, not `.metadata.annotations`.

## Actual status

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
(...)
```
## How it should be

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
  metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
  spec:
(...)
```
