### ISSUE TITLE
Add lint job

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/banzai-charts#791]
Currently helm linter only runs when a chart is being released. It might make sense in a chart monorepo, but in applications I would like to run the linter and tests for every commit.

Currently I can do that by creating my own job for linting:

```yaml
jobs:
    # ...

    lint-chart:
        executor: helm/helm
        parameters:
            chart-path:
                default: helm
                description: Path of helm chart relative to workdir
                type: string
        steps:
            - checkout
            - helm/lint:
                chart-path: << parameters.chart-path >>

workflows:
    version: 2

    # ...

    helm-chart:
        jobs:
            - lint-chart:
                  chart-path: charts/cloudinfo
                  filters:
                      tags:
                          ignore: /.*/
```

It would be nice to have a separate job running the linter.
