### ISSUE TITLE
Is it possible to define a service URL

### ISSUE THREAD

**Issue by MrD2** [banzaicloud/banzai-charts#820]
When using S3 or Goocle i can define the endpoint. 
I'm guessing this will point to the respective URLS. aws.amazon.com etc

I'm using a minio server in my cluster and i want to point to it. Is this possible to do?

Currently i'm doing something like this
```yaml
type: S3
config:
  bucket: "thanos"
  endpoint: "minio.downsampler.svc.cluster.local:9000/minio"
  access_key: "myaccesskey"
  insecure: true
  encrypt_sse: false
  secret_key: "mysecretkey"
  trace:
    enable: true
```

**Comment by MrD2** [comment]
Was missing a key objstore.config

```yaml
image:
  tag: v0.4.0
  repository: improbable/thanos

store:
  logLevel: debug
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    fsGroup: 0    
  resources: {}

query:
  logLevel: debug
  resources: {}

  ingress:
    enabled: true
    hosts:
      - subdomain.domain.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    fsGroup: 0

compact:
  logLevel: debug
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    fsGroup: 0
  resources: {}

objstore:
  provider: amazon
  configFile: "minio_aws_config.yaml"
  config: |-
    type: S3
    config:
      endpoint: "minio.downsampler.svc.cluster.local:9000"
      bucket: "thanos"
      access_key: "myaccesskey"
      insecure: true
      encrypt_sse: false
      secret_key: "mysecretkey"
      trace:
        enable: true
```
