### ISSUE TITLE
Thanos chart - missing sidecar-ingress file

### ISSUE THREAD

**Issue by idobry** [banzaicloud/banzai-charts#951]
I believe ingress file for sidecar is missing, although it can be configured in the values yaml file
Please add this:
```yaml
---
{{- if and .Values.sidecar.enabled .Values.sidecar.http.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "sidecar") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: sidecar
    {{- if .Values.sidecar.http.ingress.labels }}
  {{ toYaml .Values.ingress.http.labels | indent 4 }}
    {{- end }}
    {{- with .Values.sidecar.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.sidecar.http.ingress.tls }}
  tls:
    {{- range .Values.sidecar.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.sidecar.http.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.sidecar.http.ingress.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "sidecar") }}-http
              servicePort: {{ $.Values.sidecar.http.port }}
  {{- end }}
{{- end }}
```
Thanks,
P.S you are doing great work!

**Comment by idobry** [comment]
I actually have an update to include ingrees for grpc
```yaml
---
{{- if and .Values.sidecar.enabled .Values.sidecar.http.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "sidecar") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: sidecar
    {{- if .Values.sidecar.http.ingress.labels }}
  {{ toYaml .Values.ingress.http.labels | indent 4 }}
    {{- end }}
    {{- with .Values.sidecar.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.sidecar.http.ingress.tls }}
  tls:
    {{- range .Values.sidecar.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.sidecar.http.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.sidecar.http.ingress.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "sidecar") }}-http
              servicePort: {{ $.Values.sidecar.http.port }}
  {{- end }}
{{- end }}

---
{{- if and .Values.sidecar.enabled .Values.sidecar.grpc.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "sidecar") }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: sidecar
    {{- if .Values.sidecar.grpc.ingress.labels }}
  {{ toYaml .Values.ingress.grpc.labels | indent 4 }}
    {{- end }}
    {{- with .Values.sidecar.grpc.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.sidecar.grpc.ingress.tls }}
  tls:
    {{- range .Values.sidecar.grpc.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.sidecar.grpc.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.sidecar.grpc.ingress.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "sidecar") }}-grpc
              servicePort: {{ $.Values.sidecar.grpc.port }}
  {{- end }}
{{- end }}
```
