### ISSUE TITLE
Cadence helm chart's cadence-web service annotations are not documented and have YAML parsing errors

### ISSUE THREAD

**Issue by AgrimPrasad** [banzaicloud/banzai-charts#990]
**Describe the bug**
`web-service.yaml` template of the `cadence` helm chart wrongly parses the service annotations here: https://github.com/banzaicloud/banzai-charts/blob/c651a7200ec5084889cbffa7df87380bc7a93e06/cadence/templates/web-service.yaml#L16

This is because `{{-` removes whitespace and results in wrong YAML indentation.

**Steps to reproduce the issue:**
Add service annotations such as the following in a custom `values.yaml` file and then use `helm template`:

```yaml
web:
  ingress:
    enabled: true
  service:
    type: 'NodePort'
    annotations:
      'beta.cloud.google.com/backend-config': '{"ports":{"http":"cloud-armor-backendconfig"}}'
```

**Expected behavior**
Helm template should output valid `service.yaml` file. Insted, a YAML parsing error is shown.

Furthermore, the `web-service`'s annotations are not documented in the chart's README file.
