### ISSUE TITLE
Cadence helm chart's ingress uses deprecated apiVersion + has YAML parsing errors

### ISSUE THREAD

**Issue by AgrimPrasad** [banzaicloud/banzai-charts#991]
**Describe the bug**
`web-ingress.yaml` of the cadence helm chart wrongly parses the service name/port which results in `helm template` output containing `-webapiVersion` instead of `apiVersion` which is invalid kubernetes syntax.

https://github.com/banzaicloud/banzai-charts/blob/c651a7200ec5084889cbffa7df87380bc7a93e06/cadence/templates/web-ingress.yaml#L1-L4

**Steps to reproduce the issue:**
Enable ingress with the following in a custom `values.yaml` file:

```yaml
web:
  ingress:
    enabled: true
  service:
    type: 'NodePort'
    annotations:
      'beta.cloud.google.com/backend-config': '{"ports":{"http":"cloud-armor-backendconfig"}}'
```

**Expected behavior**
Valid ingress yaml should be generated. Instead, see the following in `helm template` output:

```yaml
# Source: cadence/templates/web-ingress.yaml
-webapiVersion: extensions/v1beta1
kind: Ingress
```

Furthermore, the ingress version is `extensions/v1beta1` which has been deprecated in Kubernetes 1.16+ Need to change to `networking.k8s.io/v1beta1` as per https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
